services:
  diarygo:
    image: diarygo:latest
    build: .
    pull_policy: never
    container_name: diarygo_app
    ports:
      - "58080:8080"
    volumes:
      - /volume1/docker/diarygo/config:/app/config
      - /volume1/docker/diarygo/data:/app/data
    environment:
      - APP_PORT=8080
      - GIN_MODE=release
    restart: unless-stopped
    networks:
      - docker_public

networks:
  docker_public:
    external: true
